name: Woc-Outposts
version: 1.0
main: com.jeepy.wocoutposts.Main
depend: [Woc-Teams]
description: A Minecraft plugin for managing outposts, loot pools, and refillable chests.
commands:
  opost:
    description: Primary command for managing outposts, loot pools, and chests.
    usage: /<command> [lootpool|MarkC|refill|start|give|stop|reload]
    aliases: [outpost]
    permission: wocoutposts.use
    permission-message: You do not have permission to use this command.

permissions:
  wocoutposts.use:
    description: Allows the use of all Woc-Outposts commands.
    default: true