name: Woc-Outposts
version: 1.0
main: com.jeepy.wocoutposts.Main
depend: [Woc-Teams]
description: A Minecraft plugin for managing outposts, loot pools, and refillable chests.
commands:
  outpost:
    description: Manage outposts (start, stop, create, delete, refill, etc.)
    usage: /outpost <start|stop|create|delete|refill|debug> [args]
  lootpool:
    description: Manage loot pool for outposts (additem, removeitem, view)
    usage: /lootpool <additem|removeitem|view> [args]